# Generated by Django 6.0.2 on 2026-02-16 02:35

import django.db.models.deletion
import restaurants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("proposed_time", models.DateTimeField()),
                (
                    "invite_code",
                    models.CharField(
                        default=restaurants.models.generate_invite_code,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-proposed_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="swipedecision",
            name="unique_user_restaurant_swipe",
        ),
        migrations.AddField(
            model_name="diningsession",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="swipedecision",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.diningsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="swipedecision",
            constraint=models.UniqueConstraint(
                fields=("session", "user", "restaurant"),
                name="unique_session_user_restaurant_swipe",
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.diningsession",
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="diningsession",
            name="participants",
            field=models.ManyToManyField(
                related_name="dining_sessions",
                through="restaurants.SessionParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "user"), name="unique_session_participant"
            ),
        ),
    ]
