# Generated by Django 6.0.2 on 2026-02-16 02:35

from django.db import migrations
from django.utils import timezone


def backfill_swipe_sessions(apps, schema_editor):
    SwipeDecision = apps.get_model("restaurants", "SwipeDecision")
    DiningSession = apps.get_model("restaurants", "DiningSession")
    SessionParticipant = apps.get_model("restaurants", "SessionParticipant")

    session_by_user_id = {}
    for swipe in SwipeDecision.objects.filter(session__isnull=True).iterator():
        user_id = swipe.user_id
        session = session_by_user_id.get(user_id)
        if session is None:
            session = DiningSession.objects.create(
                name="Imported session",
                proposed_time=timezone.now(),
                created_by_id=user_id,
            )
            SessionParticipant.objects.get_or_create(
                session_id=session.id,
                user_id=user_id,
            )
            session_by_user_id[user_id] = session

        swipe.session_id = session.id
        swipe.save(update_fields=["session"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_diningsession_sessionparticipant_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_swipe_sessions, noop_reverse),
    ]
