# Generated by Django 6.0.2 on 2026-02-16 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_backfill_swipe_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swipedecision",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.diningsession",
            ),
        ),
    ]
